### ISSUE TITLE
Something wrong with my testing package

### ISSUE THREAD

**Issue by acse-2b144a9c** [ese-msc/introduction-to-python#33]
![9e90d43c7535c88f249baa3cd5c849e](https://user-images.githubusercontent.com/110152921/182310107-41e2c96c-7d58-4079-b174-5bd22970a611.jpg)
I followed the instructions to run the courses on my laptop, but it seems that the testing package doesn't work. Should I reclone the repository? Thanks!

**Comment by marijanbeg** [comment]
Hi @acse-2b144a9c, thank you for raising an issue. The encounter the error because you do not have PyBryt and okpy installed. If you followed the installation instructions and used the `environment.yml` file we provided, then the most likely issue is that you do not start Jupyter from the right conda environment. If that is the case, you need to run `conda activate introduction-to-python` before starting Jupyter?

**Comment by acse-2b144a9c** [comment]
Thank you for responding me! I tried to activate the conda environment first, but it didn't work. I found that I can't open jupyter notebook in Anaconda Prompt. The Chinese above means that 'Juyter' is not an internal or external command nor is it a runnable program or batch files. I also tried to install okpy directly and the ProxyError was reported! Sorry, I haven't learned conda before! o(╥﹏╥)o
![a3a03d90f35ab2d6fde6db08f45a208](https://user-images.githubusercontent.com/110152921/182381678-ad65c90a-85bf-4078-9377-e3ca2697d986.jpg)
.

**Comment by acse-2b144a9c** [comment]
Thank you for responding me! I tried to activate the conda environment first, but it didn't work. I found that I can't open jupyter notebook in Anaconda Prompt. The Chinese above means that 'Juyter' is not an internal or external command nor is it a runnable program or batch files. I also tried to install okpy directly and the ProxyError was reported! Sorry, I haven't learned conda before! o(╥﹏╥)o
![a3a03d90f35ab2d6fde6db08f45a208](https://user-images.githubusercontent.com/110152921/182381678-ad65c90a-85bf-4078-9377-e3ca2697d986.jpg)
.

**Comment by marijanbeg** [comment]
Thank you for the clarification. Could you please let me know how did you create the `introduction-to-python` conda environment? Did you create it from the `environment.yml` file we provided?

**Comment by acse-2b144a9c** [comment]
I just follow the instructions and create the environment by using `conda env create -f environment.yml` . I tried to reinstall the environment today but kept reporting error.
![image](https://user-images.githubusercontent.com/110152921/182600372-fdcc83ae-cc53-41f0-aa48-d3fdc1dd6fbd.png)
Then I tried to run the course by loging to JupyterHub, the same error was reported. 
![image](https://user-images.githubusercontent.com/110152921/182602532-95d4b0b0-54cd-44eb-8f29-435a99d01c77.png)

**Comment by edsml-743ced6d** [comment]
I have met the similar problem. When I ran the "conda env create -f environment.yml", there was a window that poped up. After a long time, the pip install didn't finish and the window didn't change. 
![图片](https://user-images.githubusercontent.com/110224208/182601826-12697a90-5bf5-4416-85bc-37d73ac6e24f.png)
![图片](https://user-images.githubusercontent.com/110224208/182604497-60aa9f66-522c-4d4a-9218-d4b9a86293ca.png)

I tried to run the code one more time, but the computer reminded me that "the prefix already exists". 
![图片](https://user-images.githubusercontent.com/110224208/182602464-1514b3f7-f101-4212-845d-c8e5fab04494.png)

I guessed the virtual environment had been created. Then I followed the next step to activate the virtual environment and start up jupyter notebook. Howerver, there are still some packages uninstalled so that the error attacthed bellow came up.
![图片](https://user-images.githubusercontent.com/110224208/182603258-57ad2fed-fed0-486b-90be-9c046921c3da.png)

I speculate I should wait longer until the installation of packages in the envrionment.yml finish. I don't know whether my surmise is right. If it is right,  how long should I wait and what will showed up after the yml file disappears? If I have activated the virtual environment in advance before the yml file finished running, should I start the former steps again?
Thanks for your assistance in advance.

**Comment by marijanbeg** [comment]
Hi @acse-2b144a9c, could you please ensure you run all cells before the two cells you are attempting to execute?

**Comment by marijanbeg** [comment]
Hi @edsml-743ced6d, thank you for your question. I would suggest installing the missing packages manually in this case. You can do that by running `pip install okpy pybryt`.

**Comment by marijanbeg** [comment]
Hi @acse-2b144a9c, that is great, thank you for letting us know.

Until we resolve the issue @edsml-743ced6d encountered, we will keep this issue open.

**Comment by edsml-743ced6d** [comment]
@marijanbeg Thanks you a lot. I waited until the .yml file finished running and activated virtual environment. Now the program can run normally.
![图片](https://user-images.githubusercontent.com/110224208/182625571-442b8343-1c63-4889-b7fb-1bda57065206.png)

**Comment by marijanbeg** [comment]
Hi @edsml-743ced6d, thank you for letting me know. I will close this issue now. :)
