### ISSUE TITLE
Confusion with Exercise 3.7

### ISSUE THREAD

**Issue by acse-17b3c37e** [ese-msc/introduction-to-python#57]
I find the minimum data and maximum data here and print them out. They are exactly the number that I need but I am not sure why the pybryt test failed. They are exactly the numbers that are used in the assert test.
![p1](https://github.com/ese-msc/introduction-to-python/assets/142551505/586d91ec-0825-467b-b978-6474acfc67a5)
![p2](https://github.com/ese-msc/introduction-to-python/assets/142551505/d8116b6f-c351-4eee-b207-ce6d2a613f0f)

**Comment by marijanbeg** [comment]
Hi @acse-17b3c37e, Due to the limitations of PyBryt, we cannot provide multiple reference solutions and ensure the feedback remains understandable. Therefore, sometimes PyBryt will complain about your solution even if it is correct. So, if the `assert` statements do not raise errors, your solution is most probably correct.

**Comment by acse-17b3c37e** [comment]
Thanks for your explanation~
