### ISSUE TITLE
Using pybryt properly?

### ISSUE THREAD

**Issue by edsml-c537a607** [ese-msc/introduction-to-python#64]
I think I have installed pybryt/the necessary files to my computer incorrectly. Every time I want to check my code, in each new exercise, I have to insert a line of code that looks like this: 

pybryt_reference = '/Users/[my_name]/anaconda3/introduction-to-python/lecture1/pybryt-references/exercise-1_3.pkl' 

Obviously, replacing the file name with the appropriate one each time.

Is this standard? Or should it be accessed more naturally? I also have to remove the parentheses after the pybryt_reference call in order to make the code run (i.e. (1, 3)), which makes me think I am doing something incorrectly. 

The way I am doing it works but wanted to see if there was an easier way!

**Comment by marijanbeg** [comment]
HI @edsml-c537a607, thank you for raising this issue and for working on pre-sessional materials. It is difficult to understand what went wrong without an error message. Could you please let us know what the error message is?

Did you run the first cell in the notebook that contains `from lecture import...`, before running PyBryt cells?

**Comment by marijanbeg** [comment]
Hi @edsml-c537a607, is there any update on this issue?

**Comment by edsml-c537a607** [comment]
The exact error I get is "TypeError: 'str' object is not callable" referring to the line with pybryt.check(pybryt_reference(2, 11)). But I can fix that if I remove the (2, 11) and just use pybryt.check(pybryt_reference) with pybryt_reference defined as above

**Comment by marijanbeg** [comment]
Hi @edsml-c537a607, I believe the error you are getting is there because you redefined `pybryt_reference` to a string. However, if you run the cell at the beginning of the notebook that contains `from lecture import pybryt_reference`, it will be a function.

Could you please run the cell at the beginning of the notebook containing that line and ensure you do redefine `pybryt_reference` variable?

**Comment by marijanbeg** [comment]
Hi @edsml-c537a607, is there any update on this question?

**Comment by marijanbeg** [comment]
I will assume that this issue has been resolved, and I am closing it. Based on the conversation, this error occurred because:
1. The cell at the beginning of the notebook was not run which left `pybryt_reference` undefined.
2. `pybryt_reference` was later overwritten with a string.

Please feel free to reopen this issue if we can provide any further support on this topic.
