### ISSUE TITLE
how to assess the work

### ISSUE THREAD

**Issue by edsml-4c29515f** [ese-msc/introduction-to-python#8]
I noticed that the work will be collected due 10/8/2021, so I wonder how we submit our work? Should the work submitted in .ipynb? And where should I put the work in?

**Comment by marijanbeg** [comment]
Hi @edsml-4c29515f, thank you for your question. You will submit the notebooks in the first week after your MSc course starts, and we will teach you how to make the submission.

Could you please point us to where you found the information that the deadline is 10/08/2021 so that we can correct that? (@jrper)

Thank you very much for your feedback, and please do not hesitate to raise further issues.

**Comment by edsml-4c29515f** [comment]
hi, it's on https://ese-msc.github.io/preinduction/edsml/notebooks/python.html. The link you send us in the previous email.

**Comment by marijanbeg** [comment]
Thank you @edsml-4c29515f, the date on the webpage (8th October 2021) is correct. When you mentioned 10/08/2021, I thought we accidentally asked students to complete all notebooks until 10th August, which would be in a few days :/

Thank you very much for your valuable feedback, and please do not hesitate to raise further issues.

**Comment by marijanbeg** [comment]
@jrper, it might be worth adding a sentence describing how the work will be collected.

**Comment by jrper** [comment]
Thanks both, I've pushed an update stating that we'll explain the submission process at the beginning of induction week in October.
